### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by mr-sudaca** [willnorris/imageproxy#101]
Hello @willnorris, I've been using imageproxy for several months now, and now I have a problem. There is one image that wasn't processed correctly, and I'd like to delete the file from the cache store so it can be regenerated again, the problem is that I don't know how to look up for the file name since there are a lot of cached images on my server right now. Is there a way to know how the file name is created? I don't know go at all :-/. Thanks!

**Comment by JaosnHsieh** [comment]
Hi mr-sudaca ,
Could you tell me how you build it and make the image proxy server allow outside request?
I simply run the server by follwing commands on my Ubuntu 16.04 server.
```
go get willnorris.com/go/imageproxy/cmd/imageproxy

cd ~/go/bin

./imageproxy
```

And it shows `listening on localhost:8080`
Now I can access it on the server itself by typing
`curl http://localhost:8080/500/https://octodex.github.com/images/codercat.jpg `
It returns me the correct image file

But I cannot access it from outside network machines like
` curl http://myip.*.*.*:8080/500/https://octodex.github.com/images/codercat.jpg `
I will return
`curl: (7) Failed to connect to myip.*.*.* port 8080: Connection refused`
p.s.
I'm pretty sure the network setting is ok for outside ip access since I run a node.js server and it can be accessed through
`curl http://myip.com:8080`

Is there any setting I could do make it available from outside machines? Thanks

**Comment by willnorris** [comment]
@JaosnHsieh to listen on all network interfaces and not just localhost, pass `-addr ":8080"`

@mr-sudaca: sorry for not getting back to you here.  I'd been meaning to write some tools to make this a little easier.  The short answer is that the cache key is the md5 hash of the URL being cached.  For transformed URLs (the resized, scaled, rotated, etc) version, the fragment of the URL identifies the options.  You have to get them in exactly the right order though (see data.go).  The file on disk is stored in a two-level trie.  So if the md5 hash of the URL were "abcdef", then the file on disk would be in "ab/cd/abcdef" in whatever your specified cache directory was.

**Comment by mr-sudaca** [comment]
@willnorris np, thx for your answer!

**Comment by asepk92** [comment]
@willnorris can i change setting port 8080 to 8081 ??

**Comment by asepk92** [comment]
@willnorris can i change setting port 8080 to 8081 ??
