### ISSUE TITLE
TIFF Support

### ISSUE THREAD

**Issue by mikecx** [willnorris/imageproxy#107]
Any chance for future TIFF support?

**Comment by willnorris** [comment]
sure, wouldn't be too hard with the `golang.org/x/image/tiff` package.  You wanna take a stab at it?

**Comment by mikecx** [comment]
My Go knowledge is pretty lacking but I can certainly give it a try in a few days.

**Comment by mikecx** [comment]
#109 - Hopefully this does it, let me know if it needs changes.

**Comment by mikecx** [comment]
Looks like I misunderstood how this was working and should have tested first. If you pass in a url to a tiff image it will actually work just fine. If anyone needs tiff output it's super easy to add using the tiff package listed above.

**Comment by willnorris** [comment]
Well, it only sort of works.  If you pass it a TIFF image, it will always get passed through without any transformation, which is the same thing that happens with any unsupported format (image or otherwise).  Your point in #109 about the lack of good browser support for TIFF is interesting, and I like the idea of converting to JPEG by default.  Plus, adding proper TIFF support should also allow us to do other transformations on these images.

**Comment by willnorris** [comment]
fixed in c1a9dab40129cf41be1d7444ab3439deadb76a74
