### ISSUE TITLE
Content aware image resize

### ISSUE THREAD

**Issue by LoicMahieu** [willnorris/imageproxy#138]
Hi!

Thanks for this awesome tool!

I just came across [`caire`](https://github.com/esimov/caire) which is a "Content aware image resize library". I was wondering if it could be an alternative for [`smartcrop`](https://github.com/muesli/smartcrop) ?
I don't yet found cases where the crop is not "smart" enough but I would like to open the discussion about it.

**Comment by willnorris** [comment]
I think caire does something different than smartcrop, doesn't it?  It's about stretching and squishing the image in such a way that the most important parts of the image don't get distorted.  But as far as I know (or at least have seen in their examples) it doesn't actually crop the image.  smartcrop is about finding the right boundaries to crop the image at, but doesn't actually change the image itself in the way that caire does.

So I think they may actually be complementary.

**Comment by rrjanbiah** [comment]
@willnorris Are you suggesting that `smartcrop` will be added to `imageproxy`?

**Comment by rrjanbiah** [comment]
@willnorris Looks like you've already added `smartcrop` https://github.com/willnorris/imageproxy/blob/master/transform.go Trying to understand how to trigger it with what params...

**Comment by rrjanbiah** [comment]
@willnorris Sorry for bunch of quick messages... Found about `sc` param here https://github.com/willnorris/imageproxy/commit/afbd254cdcfc789ffac3b7df9957867c0a23e731 Looks like you've got it removed in README

**Comment by willnorris** [comment]
oops, pretty sure I didn't mean to remove those docs.  I'll get that added back.

**Comment by willnorris** [comment]
Oh, I think I see what's going on.  I remember now that I removed all of the documentation of individual options from the README file because it was just duplicating what was already in the godocs.  So instead. I just have the sentence:

> See the full list of available options at https://godoc.org/willnorris.com/go/imageproxy#ParseOptions.

The README has an example of what the smartcrop feature does, but the expectation is that users would read the above godoc page to see how exactly to use the option.  I still don't want to duplicate those docs, because then it's just more to keep in sync, but I'll see if I can find a way to more prominently link to the godocs in appropriate places.

Leaving this issue open for now to track the additional linking work.

**Comment by rrjanbiah** [comment]
@willnorris Better to keep `smartcrop` option mentioned inside the table (too)
