### ISSUE TITLE
Signature of request, should also be calculated from parameters.

### ISSUE THREAD

**Issue by krecik** [willnorris/imageproxy#145]
Currently signature is calculating only from remote url.
But this is big issue, because someone can enumerate parameters and for ex. fill up disk with cache.

Example:
```
http://imageproxy/200,s12312312313123/http://image/image.jpg
http://imageproxy/1,s12312312313123/http://image/image.jpg
http://imageproxy/2,s12312312313123/http://image/image.jpg
http://imageproxy/3,s12312312313123/http://image/image.jpg
http://imageproxy/4,s12312312313123/http://image/image.jpg
http://imageproxy/5,s12312312313123/http://image/image.jpg
http://imageproxy/6,s12312312313123/http://image/image.jpg
```

**Comment by willnorris** [comment]
yeah, this is a known issue.  The same problem exists for why it hasn't been addressed, which is that options have to be put into a canonical form for calculating the signature, but that form has never been defined.  It exists in the imageproxy code today, but it's never been publicly documented. 

And perhaps the current canonical form should be changed?  Right now it's somewhat arbitrary... options are somewhat grouped logically, but then new ones have simply been added to the end.  Maybe they should be in lexicographical order?

(I know there was discussion about this in the past at one point.  Not sure if the issue is still open.  If it is, we should probably merge this into that one)

**Comment by macovsky** [comment]
@willnorris I think even if options can be included in the signature in the same order as they're in the URL that still will be a benefit.
