### ISSUE TITLE
Add support for base URL

### ISSUE THREAD

**Issue by runemadsen** [willnorris/imageproxy#15]
It would be great if one could add a `BASE_URL` environment variable that gets added to each request. 

A call like this:

```
http://proxy/{options}/folder/myimage.jpg
```

Would get proxied like this:

```
{BASE_URL}/folder/myimage.jpg
```

That would allow us to have much nicer URL's. Would you be interested in a pull request if I add this?

**Comment by willnorris** [comment]
hmm.  okay, I sort of have mixed feelings about this.  As it is today, it's always completely obvious what source image is being proxied, which I really like.  Though I guess in a completely private installation, that's not necessarily all that important.

I know you offered to code it up, but I was curious how much complexity this would *actually* add, so I took a first pass to see, and it turns out it's actually not bad at all.  I'll open a PR myself with what I have to see if it will work for you.

**Comment by willnorris** [comment]
Also, I'm just curious... are you looking at using this for work at O'Reilly, or just personal stuff.

**Comment by runemadsen** [comment]
Awesome. I somehow didn't get notifications for this. I'm looking for an image proxy for use for O'Reilly. If you want to chat, let me know :)
