### ISSUE TITLE
Accept header seems to be missing in request

### ISSUE THREAD

**Issue by vaclav-dvorak** [willnorris/imageproxy#165]
When we try to use proxy on images from Amazon S3 cloudfront we receive 
`HTTP/1.1 403 Forbidden`
`Content-Type: application/xml`

It seems they require to receive Accept header otherwise error is thrown. this can be simulated quite easily like this:
`curl -I http://d34qiagx43sg99.cloudfront.net/5062985-745 -A "" -v -H "Accept:"`

**Suggestion:**
Would it be possible to either explicitly send `Accept : */* ` or `Accept : image/* ` or pass settings from Allowed Content-Type List?

Regards

**Comment by vaclav-dvorak** [comment]
Given command was the way we were able to reproduce behavior we experience in proxy itself. It seems cloudfront expect to receive at least some nonempty value in Accept and it seems imageproxy does not provide it.

ps:
just tried provided command again and it still return 403 forbidden:
`$ curl -I http://d34qiagx43sg99.cloudfront.net/5062985-745 -A "" -v -H "Accept:"
*   Trying 143.204.178.38...
* Connected to d34qiagx43sg99.cloudfront.net (143.204.178.38) port 80 (#0)
> HEAD /5062985-745 HTTP/1.1
> Host: d34qiagx43sg99.cloudfront.net
>
< HTTP/1.1 403 Forbidden
HTTP/1.1 403 Forbidden
< Content-Type: application/xml
Content-Type: application/xml
< Connection: keep-alive
Connection: keep-alive
< Date: Mon, 22 Oct 2018 07:44:40 GMT
Date: Mon, 22 Oct 2018 07:44:40 GMT
< Server: AmazonS3
Server: AmazonS3
< Via: 1.1 bfb6f7dc0d2f5ec95537e251cdcf5525.cloudfront.net (CloudFront), 1.1 8bb89f95ae8b94f794fb08fd2077dc5f.cloudfront.net (CloudFront)
Via: 1.1 bfb6f7dc0d2f5ec95537e251cdcf5525.cloudfront.net (CloudFront), 1.1 8bb89f95ae8b94f794fb08fd2077dc5f.cloudfront.net (CloudFront)
< X-Cache: Error from cloudfront
X-Cache: Error from cloudfront
< X-Amz-Cf-Id: g5pOjOLHsFpm8D9pc098AynkiTKT7MA3rhUeERUm2ri6gBE5kf0a2Q==
X-Amz-Cf-Id: g5pOjOLHsFpm8D9pc098AynkiTKT7MA3rhUeERUm2ri6gBE5kf0a2Q==

<
* Connection #0 to host d34qiagx43sg99.cloudfront.net left intact`

**Comment by willnorris** [comment]
Sorry, I completely goofed in my example.  What I meant to include was:

```
curl -I http://d34qiagx43sg99.cloudfront.net/5062985-745 -A "" -v

HTTP/1.1 200 OK
```

The error only seems to occur if there is an Accept header with a zero value, as in the command you provided.  But when there is no Accept header at all (which is what *should* happen with imageproxy), then the error goes away.

Do you know for sure that the curl command you provided actually exemplifies the kind of request imageproxy is sending?  Because there's nowhere in the code that I can find that would result in an empty Accept header being sent.  I don't doubt that you're having some issues proxying images from cloudfront, I'm just trying to make sure that this is actually where the problem lies.

**Comment by summituk** [comment]
Hi,
Basically, I think the imageproxy should sent "Accep: image/*" request header when downloading images.
