### ISSUE TITLE
Cannot operate on an image

### ISSUE THREAD

**Issue by adrian727** [willnorris/imageproxy#20]
We tried to operate on this url, all operations (resize, crop, rotate) failed, please help
https://photos.hotelbeds.com/giata/bigger/13/139735/139735a_hb_a_001.jpg

**Comment by willnorris** [comment]
do the error logs tell you anything?  (If you're not seeing anything in stderr, you may need to pass the flag `-alsologtostderr`)

**Comment by willnorris** [comment]
err, nevermind.  I was going to say that it's working fine for me, but now I see that my operations are failing also.  I'll look into it.

**Comment by willnorris** [comment]
According to https://github.com/golang/go/issues/2362 and https://groups.google.com/d/topic/golang-nuts/1MlciQhU2QA this has been fixed in go tip (and will be in the go1.5 release).  I'll try to confirm that this image is handled properly.

**Comment by willnorris** [comment]
okay, so this is definitely fixed in go tip.  here's with go 1.4.2

![screen shot 2015-03-17 at 11 19 10 pm](https://cloud.githubusercontent.com/assets/1112/6703677/313f85c8-ccfc-11e4-92f4-20558f9d5a98.png)

And here's with go tip (`go version devel +ecd630d Wed Mar 18 00:59:49 2015 +0000 darwin/amd64`):

![screen shot 2015-03-17 at 11 19 29 pm](https://cloud.githubusercontent.com/assets/1112/6703684/407aa11c-ccfc-11e4-8839-a8d479dad5ae.png)

So there's not much to be done except either you build and run the latest go code, or wait for the 1.5 release.
