### ISSUE TITLE
imageproxy URLs can't be served by imageproxy

### ISSUE THREAD

**Issue by aaronpk** [willnorris/imageproxy#212]
If two separate websites are both using imageproxy for images, then it turns out that nesting these URLs fails due to the way the URL parsing works.

For example, a website publishes an image URL in a feed such as

```
https://img.example.net/w_960,c_fill/https://media.example.net/3def0f60f.jpg
```

Then a feed reader finds that image URL and serves it up from its own imageproxy, creating a URL like

```
https://images.reader.example/1240x0/https://img.example.net/w_960,c_fill/https://media.example.net/3def0f60f.jpg
```

This fails because it's unable to recognize where the parameters from the first imageproxy end and the next one start.

**Comment by willnorris** [comment]
relevant IRC discussion: https://chat.indieweb.org/meta/2020-01-26#t1580074016503900

I think this is a problem with the signature verification and the use of single versus double slashes in embedded URLs.  [Relevant code here](https://github.com/willnorris/imageproxy/blob/c2dd07958424b20871f270affa867f08348e9134/data.go#L378), and I suspect I may just need to replace the first instance of "https:/", rather than all of them.  I'll test this out shortly.
