### ISSUE TITLE
Hosts management with Reverse Porxy 

### ISSUE THREAD

**Issue by Calx-Takeno** [willnorris/imageproxy#279]
Hi, I use a reverse proxy to transfer the request to imageproxy. Maybe a bit complicated deployment

mydomain.com (reverse proxy with SSL) -> 127.0.0.1:8080 (imageproxy listen) -> baseURL 127.0.0.1:9000 (minio listen)

Causes the reverse proxy to unmount the original host reference, so I cannot use the -allowHosts or -denyHosts feature

Colud I bind the host to imageproxy directly without a reverse proxy? Such as with SSL certification?

'imageproxy -addr mydomain.com -baseURL http://127.0.0.1:9000 -allowHosts example.com'

would be wrong.

**Comment by willnorris** [comment]
running imageproxy behind a proxy to do SSL termination is a pretty standard way to run it, so that shouldn't be causing any problems.  What do you mean by "Causes the reverse proxy to unmount the original host reference"?  I'm not following what's happening there.

Just looking at your flags, one thing that is likely causing problems is that your base URL has a hostname of "127.0.0.1", but you're only allowing remote URLs of "example.com".  What happens if you add "127.0.0.1" as an allowed host?  (I can't remember if that all works with IP addresses and localhost URLs, but I think it should)

**Comment by Calx-Takeno** [comment]
Oh~
I think I am using the feature --allowHosts wrongly .
I want to prevent hotlinking, I should use the -referrers.
Please close the issue. Thank you.

**Comment by Calx-Takeno** [comment]
> Oh~
> I think I am using the feature --allowHosts wrongly .
> I want to prevent hotlinking, I should use the -referrers.
> Please close the issue. Thank you.


Another question is how to bypass the request of the APP scenario?
The request from the app may not contain the referrer URL

**Comment by willnorris** [comment]
you can bypass the referrer check by signing the URLs: https://github.com/willnorris/imageproxy#signed-requests

**Comment by Calx-Takeno** [comment]
Thank you. It works

> you can bypass the referrer check by signing the URLs: https://github.com/willnorris/imageproxy#signed-requests
