### ISSUE TITLE
HEIC support?

### ISSUE THREAD

**Issue by sarnobat** [willnorris/imageproxy#292]
Are there any plans to support the HEIC image format which Apple iPhone uses?

This tool was working beautifully for my workflow until I realized this. More so than other image proxying tools.

**Comment by willnorris** [comment]
No immediate plans, but I'm not fundamentally opposed to it.  The problem is the same as with webp (#114), which is that there is no native Go library that supports it, and I'm avoiding cgo in this project right now.  

The above issue has some discussion about a one-day-maybe rearchitecture of imageproxy that would make it possible to write plugins similar to [caddy](https://github.com/caddyserver/caddy).  That issue also discusses other projects that might work better for some use cases, but it sounds like you may have explored some of those already.

**Comment by sarnobat** [comment]
Thanks for the info. Hopefully someone will create a native Go library for this in the near future.

Since this tool is so nice as it is I'm not sure whether rearchitecture would spoil that. I've had a bad experience with runtime dependencies (which is why I like golang's static linking).
