### ISSUE TITLE
Add a content type check

### ISSUE THREAD

**Issue by toubib** [willnorris/imageproxy#53]
We should use [http.DetectContentType](https://golang.org/pkg/net/http/#DetectContentType) to verify the content type and return an error if not an image.

See PR #42 for request background.

**Comment by kbariotis** [comment]
Hello @Toubib. I thought I would give this a try. Hope none else is working on it. I just starting learning Go and here's my [progress](https://github.com/willnorris/imageproxy/compare/master...kbariotis:add-mimetype-check) so far. Still needs work ofc.

**Comment by willnorris** [comment]
@kbariotis, a few observations on what you have so far:

 - you're currently calling `http.DetectContentType` for each type that you're checking against.  It's not going to change, so should just be called once, and then tested against each value

 - this should be user configurable, similar to how host whitelist and referer are.  At least initially, I think the default should be to not check (see next point), so that this doesn't become a breaking change for anyone.

 - mime type checking should be able to be disabled entirely (the current behavior today), probably by simply specifying an empty set of types

 - eventually (could be a future enhancement), we should probably support wildcards, such as "image/*".  I think atmos/camo use to do this kind of wildcard check, but ended up moving away from it in favor of their [explicit list of supported types](https://github.com/atmos/camo/blob/master/mime-types.json).  It would be worth trying to find the issue that motivated that change to make sure we don't needlessly repeat the same mistake.

**Comment by willnorris** [comment]
and `http.ErrBodyNotAllowed` is not the right error here.  As noted in the [text for that error](https://golang.org/pkg/net/http/#pkg-variables), that's for when the HTTP method or status code is not supposed to have a body at all, but one is present.

Thanks for taking a stab at this though... it looks like a good start.

**Comment by kbariotis** [comment]
@willnorris thank you. Will fix those. 

A quick question, though. Similar to host whitelist and referrer, an `MIMETypes` array should go to the Proxy struct. How should I access the Proxy object from inside the RoundTrip function in order to get the MIMETypes array? Is there another route I can take?

**Comment by willnorris** [comment]
hmm.  #37 did something pretty similar by adding a pointer from the TransformingTransport to the Proxy instance.  I actually end up refactoring that in b4216d8da8572c3d605c25f7fe6610f27aa720ec to not need that pointer, since I didn't (and generally still don't) like having the TransformingTransport type tied that tightly to the Proxy type.  I'll have to think a bit more to see if I can come up with a cleaner way to do that.

**Comment by kbariotis** [comment]
Keep me in the loop then @willnorris. I would love to contribute to it. :) My branch is updated and ready to PR.

**Comment by willnorris** [comment]
content type checking added in 39a4e1813d91754d4a514d1032433c644315e9eb and 0370572130f47c5517841c9041264a6d4338174d
