### ISSUE TITLE
S3

### ISSUE THREAD

**Issue by mdaymond** [willnorris/imageproxy#58]
I'm having trouble configuring S3 caching.   Can you confirm I am using the correct syntax ?   I have verified my S3 permissions and connected from this instance using the AWS SDK.   My access key and security key are setup via **aws configure.**

**Start Command**
imageproxy/bin/imageproxy -cache s3://s3.amazonaws.com/zone-dropbox/output/cm/image-cache/ -addr 10.138.107.125:8080 

**Error**
2016/04/11 22:00:46 s3util.Create failed: unwanted http status 403: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId></AWSAccessKeyId><RequestId>AEAC7AA329BBE037</RequestId><HostId>tEBB1ELYxnC8PD5lT1JHhO02so4ZWyB3Vw+tIfQl2GPbs0398kR+S+7VFhoJy7Wzc5azjN/I0N0=</HostId></Error>

**Comment by willnorris** [comment]
You either need to use an instance profile (when you're actually running on EC2), or the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY` environment variables.  

[aws configure](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html) populates a `~/.aws/credentials` file which is specific for the aws CLI.  imageproxy doesn't read from that file.

**Comment by mdaymond** [comment]
Thanks.  I did try exporting/setting the environment variables as well and that didn't work either.    Still getting a 403.  I have verified the permissions outside of imageproxy and everything seems fine.

**Comment by noogen** [comment]
Can you try without any folder?  Check my run configuration here:  https://github.com/trybrick/imageproxy/blob/master/scripts/run.sh

Use:
```
-cache s3://s3.amazonaws.com/zone-dropbox
```

Reason:  When I look at the s3 cache module, it look like the code is using the entire bucket.  It doesn't seem to work with bucket subfolder.  Therefore, you should reserve a bucket for the cache.

If you think about it, it makes a lot of sense why they did it this way for performance.  This is because s3 partition (storage location) by the first n (usually 3) characters.  S3 cache module use guid to represent the URL it is caching and for storage performance.

**Comment by mdaymond** [comment]
Thanks.. this is solved.
