### ISSUE TITLE
Display default 404 image if not loaded 

### ISSUE THREAD

**Issue by themetric** [willnorris/imageproxy#67]
In the case of using the proxy URL in an email, it would be nice to show a default image if the external image 404s.  While this may be possible to set on a server, I don't think it's possible to set a 404 image within an email.  

Currently the service returns the 404 content (even HTML!) of the external site when requesting a bad image.  Is there any way around this?  Happy to submit a PR to add this functionality.

**Comment by willnorris** [comment]
they way you would typically set this up is to run imageproxy behind a web server like nginx, and configure a 404 handler in nginx that returns a default image.  That's all happening server side, so wouldn't make a difference if it is in a webpage or an email.

**Comment by themetric** [comment]
Great idea!  I have apache running a reverse proxy to Docker.  So I guess I would set the 404 handler there in Apache?

**Comment by willnorris** [comment]
yep, that should work

**Comment by themetric** [comment]
I've been struggling to get the correct Apache configuration, but even so it seems like there should be a way to do this within the service itself.  For instance a situation like this: 

http://localhost:8080/300/https://google.com/

Returns a webpage instead of an image and since the status code is 200-OK it's hard to intercept it and set to a default image.

**Comment by willnorris** [comment]
> http://localhost:8080/300/https://google.com/
> 
> Returns a webpage instead of an image and since the status code is 200-OK it's hard to intercept it and set to a default image.

What's actually wrong with returning an HTML page here?  That's the URL that was requested.  While outside the scope of what imageproxy was intended for, using it to proxy other types of content can be useful, particularly to prevent insecure content issues for https pages.  #53 is discussing adding a content type check that would allow you to explicitly lock imageproxy down to serving only images (or other types), which would address this case.

However, I'm still not convinced that it's imageproxy's job to serve a default image, since that masks upstream errors.  Especially given how trivial this is to do within a webserver.  For Apache, I think you want to set an [ErrorDocument](https://httpd.apache.org/docs/2.4/mod/core.html#errordocument).

**Comment by themetric** [comment]
Agreed, I think the content type check would be nice and the remaning errors should be handled by the webserver.  For some reason ErrorDocument hasn't been too reliable for me but I'll keep trying.  thx!
