### ISSUE TITLE
baseUrl with file scheme (local file)

### ISSUE THREAD

**Issue by emaniacs** [willnorris/imageproxy#73]
is there a possibility using **file://** scheme on baseUrl (localfile)?

**Comment by willnorris** [comment]
imageproxy was always specifically designed to proxy images that are already publicly available on the web.  Adding support for proxying file URLs would be a significant amount of work since the http package doesn't support it, and I wouldn't want to add the additional complexity to imageproxy even if the http package did support it.  Thanks for the interest though.

**Comment by emaniacs** [comment]
I know, this project created to proxy images that are already publicly available on the web, but i use it mainly for managing/resizing image, thats why iam asking for it.

Btw, thanks for clarification.

**Comment by Spiralis** [comment]
@emaniacs We are interested in the same. Did you ever find a solution?

@willnorris I don't know Go, but which API call do you use to fetch the original url? Maybe the API call knows how to handle custom protocol urls?
