### ISSUE TITLE
Get output as JPEG

### ISSUE THREAD

**Issue by mbn18** [willnorris/imageproxy#89]
Is it possible to request a JPEG output.

I have use cases where the users upload big PNG files and such conversation on the fly could save considerably large bandwidth.

**Comment by willnorris** [comment]
No, imageproxy doesn't do any format conversion... images are always re-encoded in the same format as the original.  Though with #88, we may need to add support for this (as much as I generally prefer to limit the number of extraneous options).

**Comment by mbn18** [comment]
So is it expected?
Lets assume I hook up a bank of big PNG files or other uncompressed extension. Type conversion could be crucial in such scenarios.

**Comment by willnorris** [comment]
PNG is actually compressed, but it's lossless.  Converting to a lossy format like JPEG is going to reduce the image quality substantially in many cases.  If the type of image you're dealing with is better suited for a lossy format like JPEG, why not use that for the source image as well rather than PNG?

You have to remember that imageproxy was designed to handle basic resizing and manipulations like rotation and flipping; that's it. (I'm open to adding format conversion because it's needed for webp support, but it was never a design goal of the package)

**Comment by mbn18** [comment]
Its kinda the gap between theory and reality.
In theory yea, PNG should be used where PNG is appropriate and the repo should be clean.
But clueless/careless users upload variety of files and in some cases they even upload PNG files with `.jpg` extension. And not always the gateway keepers know how to validate/transform and etc.

Thanks for the consideration

**Comment by noogen** [comment]
Had the same requirement.  I also needed crop with gravity so I created - https://github.com/niiknow/docker-nginx-image-proxy/ - inspired by imageproxy project and cloudinary.  If you pass in quality less than 96 (default) then it automatically convert to jpeg.
