### ISSUE TITLE
Auto expiry of items in the disk cache.

### ISSUE THREAD

**Issue by JamieH** [willnorris/imageproxy#9]
If using the disk cache, once the disk cache hits 100MB of usage the http server will lock up and not serve new requests because the disk cache is full.

**Comment by shepik** [comment]
Hi. I don't know if this is an issue in upstream, but

ps auwx | grep imageproxy
./imageproxy -addr=... -secret_sign=... -secret_key=.. -cacheDir=/var/cache/imageproxy -cacheSize=1000 -logtostderr=true

du -hs /var/cache/imageproxy
69G     /var/cache/imageproxy

I don't see any errors. But this might be related to my cache changes (https://github.com/willnorris/imageproxy/issues/28#issuecomment-104370112 - or might be not - i don't know how diskv decides what items to evict)

Is there anyone experiencing similar problems?

**Comment by willnorris** [comment]
@shepik: yes, others are running into this as well.  Tracking it in #45.

**Comment by willnorris** [comment]
closing this issue as #45 is now resolved (in the sense that the `cacheSize` flag was never actually doing what I thought all along).  As to the original suggestion in this issue, auto-purging expired entries, I'm not sure how that would be possible since the [`httpcache.Cache`](https://godoc.org/github.com/gregjones/httpcache#Cache) interface has no way to iterate over all the entries in the cache to find the expired ones.
